release-date = "2022-12-01"

[[entries]]
id = "e3943f03-f617-4439-9f3f-6150a9355292"
type = "feature"
description = "add `--state-dir`, `--additional-state-dir` and `--no-load-project` options"
author = "@NiklasRosenstein"

[[entries]]
id = "d9331301-07f4-4171-9541-70d38c8d1ebd"
type = "feature"
description = "add `--state-name` option"
author = "@NiklasRosenstein"

[[entries]]
id = "e2245832-f7e2-4178-bc27-83a8525d6c11"
type = "fix"
description = "fix merging the results of multiple build states into a single graph"
author = "@NiklasRosenstein"
