release-date = "2022-12-01"

[[entries]]
id = "07911bd1-8d7b-4cbb-8795-131a1dd76cb8"
type = "improvement"
description = "use argparse argument groups in kraken cli"
author = "@NiklasRosenstein"

[[entries]]
id = "2730e914-5938-4c99-8cdc-2f1ce123e53f"
type = "improvement"
description = "migrate to `Supplier` class in `nr-stream` package"
author = "@NiklasRosenstein"
