release-date = "2022-12-19"

[[entries]]
id = "0c121da7-a451-4fba-81fa-fb57ad3ccaf9"
type = "improvement"
description = "Refactor, moving `kraken.core.{executor,context,graph,project,property,supplier,task}` to `kraken.core.system` subpackage (renaming `supplier` to `task_supplier`). Added the `kraken.core.api` module which should be used for public imports, any imports from members of the `kraken.core` package not from `kraken.core.api` are not officially supported."
author = "@NiklasRosenstein"

[[entries]]
id = "c43464f2-b07c-4705-a889-9676d48ed70b"
type = "improvement"
description = "add backwards compatibility layer for code making imports to kraken.core submodules"
author = "@NiklasRosenstein"

[[entries]]
id = "3bf3644f-f3de-4c4e-85a9-39e0eeba244d"
type = "improvement"
description = "rename kraken.core.test to kraken.core.testing (keep kraken.core.test for backwards compatibility)"
author = "@NiklasRosenstein"
