release-date = "2022-12-19"

[[entries]]
id = "2ae4cd9f-b3ec-452a-9c81-411bf26add4d"
type = "improvement"
description = "upgrade to kraken-common 0.5.2"
author = "@NiklasRosenstein"

[[entries]]
id = "b0b92915-b5b1-4c79-94c5-7b80c879f5b9"
type = "feature"
description = "add `Context.get_project()` and update `Context.resolve_tasks()` to always resolve task references beginning with a `:` as absolute (always relative to the root project)"
author = "@NiklasRosenstein"

[[entries]]
id = "0f9b698b-bc8d-48c3-9d9e-77d9e77ef3b5"
type = "feature"
description = "using the `-p,--project-dir` option now has Kraken change directory to the specified path but by default only select tasks in the respective subproject represented by the current working directory and relative task references are taken relative to that subproject as well"
author = "@NiklasRosenstein"

[[entries]]
id = "3522931f-54d3-455d-bb15-2016f7780562"
type = "feature"
description = "`Project.do()` now accepts a `builddsl.UnboundClosure` as third argument (overlapping with the `default` argument)"
author = "@NiklasRosenstein"
