release-date = "2022-12-14"

[[entries]]
id = "2bca2dd0-bd7c-417b-941d-c9cda9604e3e"
type = "feature"
description = "add `Project.has_subproject()`"
author = "@NiklasRosenstein"

[[entries]]
id = "4c4ab6d3-49a9-4bd1-8721-4908b41313c0"
type = "breaking change"
description = "move all members of the `kraken.core.util` package to the `kraken.common` package; note that `kraken.util.supplier` is now available from the `nr.stream` package"
author = "@NiklasRosenstein"

[[entries]]
id = "90967be9-a53e-49e6-a0de-a696e897fb23"
type = "breaking change"
description = "remove `ProjectLoader` interface, instead use the new `ScriptRunner` interface from the `kraken.common` package"
author = "@NiklasRosenstein"

[[entries]]
id = "848eb422-7762-4f13-a995-a9af1dc32b1c"
type = "feature"
description = "Kraken build scripts can now be written using [BuildDSL](https://pypi.org/project/builddsl/) (using the `.build` instead of `.py` suffix)"
author = "@NiklasRosenstein"

[[entries]]
id = "b0d74f1f-0375-4747-8cf0-0e034f2e7181"
type = "feature"
description = "support for the `kraken.common.buildscript()` function to update `sys.path`"
author = "@NiklasRosenstein"
