release-date = "2022-07-10"

[[entries]]
id = "c5ce91f3-cd21-4e95-ae0f-b80b5f6624bb"
type = "fix"
description = "Fix multiple inheritance alongside `kraken.core.property.Object`"
author = "@NiklasRosenstein"
