release-date = "2022-07-08"

[[entries]]
id = "b473bf0d-3dd0-4577-806a-ac34b717ac7d"
type = "improvement"
description = "Look for `kraken.build.py` scripts in addition to `kraken.py`, the latter can result into issues resolving the `kraken` package as the build script can take precedence"
author = "@NiklasRosenstein"

[[entries]]
id = "c3d3f28b-cfc6-41ed-a4bb-78d91c2c4199"
type = "feature"
description = "add `Project.metadata` and `Project.find_metadata()` which can be used by plugins to store project-global data"
author = "@NiklasRosenstein"

[[entries]]
id = "17096f81-b3a8-439b-9c5f-873504172a4c"
type = "improvement"
description = "improve VSCode type recognition for `Task.project` by putting `typing.ForwardRef()` for `Project` in the else block of `if TYPE_CHECKING:`"
author = "@NiklasRosenstein"

[[entries]]
id = "9381d8ca-0b63-40fc-9404-48142b84172d"
type = "feature"
description = "add `kraken.core.utils.atomic_file_swap()`"
author = "@NiklasRosenstein"
