release-date = "2022-07-06"

[[entries]]
id = "920fe0e8-3852-4df3-820c-1f3595a50863"
type = "feature"
description = "install requirements.txt into .build/.lib directory if a .kraken/requirements.txt file exists"
author = "@NiklasRosenstein"

[[entries]]
id = "9dc07eb6-b564-4212-8d0b-f71bee8d42e4"
type = "feature"
description = "implement Path value adapters"
author = "@NiklasRosenstein"

[[entries]]
id = "1297f956-619f-4806-a963-5392c82d5c78"
type = "improvement"
description = "add derived_from to of_callable(), setdefault() no longer returns a value"
author = "@NiklasRosenstein"
