release-date = "2022-07-19"

[[entries]]
id = "9b24e0cd-b5bd-47c1-be0a-235b090162f5"
type = "breaking change"
description = "a rather substantial refactor to rename `BuildContext` to just `Context` and `BuildGraph` to `TaskGraph`, removed the `task_factory` class and moved its functionality mostly to `Project.do()`"
author = "@NiklasRosenstein"

[[entries]]
id = "7231d9fd-b2fe-4ba7-b1f4-22985d0082b3"
type = "breaking change"
description = "move `kraken.testing` to `kraken.core.testing`"
author = "@NiklasRosenstein"

[[entries]]
id = "e32c6921-0d5d-4041-b95e-4de2ad42fa4d"
type = "feature"
description = "add simple CLI that can be run with `python -m kraken.core`"
author = "@NiklasRosenstein"

[[entries]]
id = "8985b797-3638-42f1-9921-9b9a8a501fda"
type = "improvement"
description = "flush after printing in Executor to ensure that outputs are in order (sometimes an issue in CI jobs on Github and Gitlab)"
author = "@NiklasRosenstein"
