release-date = "2022-07-24"

[[entries]]
id = "987976f2-3729-4247-84b4-9abff032ce67"
type = "feature"
description = "allow adding question marks to target selectors to make it optional"
author = "@NiklasRosenstein"

[[entries]]
id = "9a9905f6-a4eb-4804-979e-050adfe297f3"
type = "improvement"
description = "improve `ValueError` raised when task selector is resolved in `Task.get_relationships()` to add the context of the task that the selector is resolved from"
author = "@NiklasRosenstein"

[[entries]]
id = "65ef243f-292b-44c9-bb60-2cc8a280dec9"
type = "breaking change"
description = "rename `TaskResult` to `TaskStatusType`"
author = "@NiklasRosenstein"

[[entries]]
id = "9fcccaaf-7d73-4cd8-bcc7-9e54f21bbb9d"
type = "breaking change"
description = "add `TaskStatus` type"
author = "@NiklasRosenstein"

[[entries]]
id = "cbda1e03-6075-4eb8-912c-690774b99061"
type = "breaking change"
description = "replace `Task.is_up_to_date()` and `Task.is_skippable()` with new `Task.prepare()` method"
author = "@NiklasRosenstein"

[[entries]]
id = "76cbd68e-dc66-45c1-bdef-340ec5253443"
type = "breaking change"
description = "`Task.execute()` can now return `None` to indicate success"
author = "@NiklasRosenstein"

[[entries]]
id = "67e2fee0-3a6d-4c6c-ae6a-75b5a52279f3"
type = "breaking change"
description = "The `TaskGraph` now tracks task statuses and can be used to query remaining tasks (added `TaskGraph.set_status()`, `TaskGraph.get_status()`, `TaskGraph.is_complete()` and `TaskGraph.ready()`"
author = "@NiklasRosenstein"

[[entries]]
id = "e076a6fb-b24f-4525-98ee-7383836a0a82"
type = "feature"
description = "The `Executor` now by default executes as many tasks as possible instead of failing on the first (this is enabled by the new `TaskGraph` API)"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/kraken-build/kraken-core/issues/1",
]

[[entries]]
id = "78f3be70-ca67-4521-a6cf-e784a4cfbe6e"
type = "improvement"
description = "add `TaskStatusType.PENDING`"
author = "@NiklasRosenstein"
