release-date = "2022-07-27"

[[entries]]
id = "5e3bdc46-4b82-43b5-a20a-34b2e6b1fb68"
type = "improvement"
description = "Move `.find_metadata()` and `.current()` implementation on `Context` and `Project` into common base classes (`MetadataContainer` and `CurrentProvider`), add `Project.default()` and `Project.default_factory()`, add `Property.setcallable()` and `Property.clear()`"
author = "@NiklasRosenstein"

[[entries]]
id = "754f7b7e-c8d6-474e-838e-65366961fd6c"
type = "feature"
description = "Add `Task.teardown()` method and adapt `Executor` to call it"
author = "@NiklasRosenstein"

[[entries]]
id = "dca7db79-7192-4be6-9657-3829d457a07a"
type = "feature"
description = "`VoidTask` can now be configured to not skip execution"
author = "@NiklasRosenstein"

[[entries]]
id = "8926138b-c0f4-4118-a066-4ae03e207974"
type = "feature"
description = "Add `TaskStatusType.STARTED`"
author = "@NiklasRosenstein"

[[entries]]
id = "c12c3e9e-014a-4afe-bb5f-7ae076b69991"
type = "feature"
description = "add `BackgroundTask` base class"
author = "@NiklasRosenstein"
