release-date = "2022-07-24"

[[entries]]
id = "d98cf5b6-2fda-405a-9dc8-ac9f64994c2f"
type = "improvement"
description = "make sure anonymous `Supplier` subclasses are picklable"
author = "@NiklasRosenstein"

[[entries]]
id = "70bf851c-f363-42c2-bec0-6aa1ea426325"
type = "breaking change"
description = "revamp `TaskGraph` API"
author = "@NiklasRosenstein"
