release-date = "2022-08-06"

[[entries]]
id = "51093178-3eb5-42a8-a08a-482f3442d7f3"
type = "improvement"
description = "Fix a potential error when a bad value is passed to `Property.default()` on construction of the object where it cannot be properly formatted as a string yet because some attributes may not be set; `Property.__repr__()` now catches an exception of formatting it's owner"
author = "@NiklasRosenstein"

[[entries]]
id = "08cb456c-2355-4861-b281-5dc9e54a06e2"
type = "fix"
description = "In the previous version, the default groups `lint` and `test` should have been marked as default tasks. They are now"
author = "@NiklasRosenstein"

[[entries]]
id = "1a2b9ead-f48b-406e-ad10-15b72fa98d3a"
type = "improvement"
description = "`TaskGraph.set_targets()` now longer treats group tasks special; this allows `TaskGroup.tasks(targets_only=True)` to return the group tasks that were originally passed into `set_targets()`"
author = "@NiklasRosenstein"
