release-date = "2022-08-04"

[[entries]]
id = "c52ddf70-b8c6-4aa1-934f-518e8331a029"
type = "fix"
description = "Fix default executor to now print build summary in execution order"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/kraken-build/kraken-core/issues/4",
]
