release-date = "2022-08-30"

[[entries]]
id = "e317e2d0-f9e8-4fd1-ac94-5963c66a8ecd"
type = "tests"
description = "add unit test for subclasses of `Object` that do not have annotations, this fails with `typeapi <= 0.2.1` in Python <=3.9. That is why we now require `typeapi ^0.2.2`"
author = "@NiklasRosenstein"

[[entries]]
id = "5114f5fd-3301-4743-ad65-1bd8b228de10"
type = "improvement"
description = "add task status message when `RenderFileTask` is up to date"
author = "@NiklasRosenstein"
