release-date = "2022-08-23"

[[entries]]
id = "41708edf-66dc-4686-8bdc-acc5640e6031"
type = "improvement"
description = "remove `--no-save` option from `kraken query` commands, the build state will never be saved after these commands"
author = "@NiklasRosenstein"

[[entries]]
id = "ee29315b-26e7-42ca-8d92-31afab208cad"
type = "improvement"
description = "Task groups that depend on other task groups will not create an implicit dependency between the downstream group and the **tasks** in the downstream group and the downstream group. Added a concept of \"implicit\" edges to the `TaskGraph`"
author = "@NiklasRosenstein"

[[entries]]
id = "f84f9107-4a62-49a3-8c20-ecfbdaeb3ae1"
type = "feature"
description = "added `kraken q v -R,--reduce` and `-r,--reduce-keep-explicit` options and `TaskGraph.reduce()` method"
author = "@NiklasRosenstein"
