release-date = "2022-08-17"

[[entries]]
id = "ec8d4649-92c5-4f36-8401-af2f9025c34e"
type = "fix"
description = "pin networkx down to 2.6.x which is the last version with Py 3.7 compatibility"
author = "@NiklasRosenstein"

[[entries]]
id = "dfd371fb-27c4-449f-9a0c-06e6427bcf23"
type = "feature"
description = "add `RequirementSpec.replace()`"
author = "@NiklasRosenstein"
