release-date = "2022-08-12"

[[entries]]
id = "875405ee-9232-49b3-a93b-e92f4e64d294"
type = "fix"
description = "disable Pip fast-deps feature for Pex resolves, can lead to bad resolves"
author = "@NiklasRosenstein"

[[entries]]
id = "d5439c4c-59c4-48ec-a50e-26d1d526389b"
type = "improvement"
description = "add support for `KRAKENW_INCREMENTAL` flag"
author = "@NiklasRosenstein"
