release-date = "2023-01-22"

[[entries]]
id = "5c3f32cd-4717-4fa9-a76c-43864abfafce"
type = "feature"
description = "add Windows support by conditionally importing/supporting PEX environment"
author = "@Nairu"
