release-date = "2022-07-22"

[[entries]]
id = "e3db4ba1-6bae-4a51-830d-3ec9933e0980"
type = "improvement"
description = "Pass `--no-interacton` to `poetry install`"
author = "@NiklasRosenstein"

[[entries]]
id = "a4c62889-e571-45b7-9420-5b407de84aa6"
type = "fix"
description = "Python install task now understands the `PythonSettings.always_use_managed_env` option"
author = "@NiklasRosenstein"
