release-date = "2022-07-27"

[[entries]]
id = "b5816d6a-aed0-4af8-8d34-93dd5548d836"
type = "feature"
description = "add a `GitignoreSyncTask`"
author = "@NiklasRosenstein"

[[entries]]
id = "9cf67034-f6f6-497c-bf4d-b0c7bf319f4c"
type = "breaking change"
description = "rework Cargo API"
author = "@NiklasRosenstein"
