release-date = "2022-08-03"

[[entries]]
id = "69248842-86ff-404c-bc06-bedfe5c0e257"
type = "feature"
description = "add `GitVersion.format()`"
author = "@NiklasRosenstein"

[[entries]]
id = "faa61b89-ada1-431f-970e-147e240810e8"
type = "improvement"
description = "update `helm_package()`"
author = "@NiklasRosenstein"
