release-date = "2022-07-13"

[[entries]]
id = "195cd20a-f4ad-4906-ab46-3d797bd388b1"
type = "fix"
description = "actually handke `KanikoBuildTask.kaniko_copy_cache_layers` option"
author = "@NiklasRosenstein"
