release-date = "2022-08-01"

[[entries]]
id = "0f4e88cc-1671-4dab-a449-5dea3a0f8d8b"
type = "hygiene"
description = "remove unused `CargoAuthProxyTask.for_tasks` and `CargoSyncConfigTask.for_tasks`"
author = "@NiklasRosenstein"

[[entries]]
id = "598f2ab5-4be0-4784-a918-5024bb1e7d58"
type = "improvement"
description = "update Cargo MITM proxy to not inject credentials into CONNECT requests"
author = "@NiklasRosenstein"

[[entries]]
id = "1aa1e30b-4057-41f6-92b3-fb25e245a726"
type = "feature"
description = "add `CargoSyncConfigTask.git_fetch_with_cli` property"
author = "@NiklasRosenstein"

[[entries]]
id = "c0b838ab-1f9e-4269-bcaf-fd7c8fb3297a"
type = "fix"
description = "avoid revealing secret in `CargoBuildTask` and `CargoPublishTask` result status message"
author = "@NiklasRosenstein"

[[entries]]
id = "42c428e5-3c78-4de5-a37a-505b2db79812"
type = "fix"
description = "fix showing sccache stats when the sccache server is stopped"
author = "@NiklasRosenstein"

[[entries]]
id = "78e3d494-b9e1-4758-a6e0-136a05ff3a93"
type = "fix"
description = "fix passing args to `CargoBuildTask`"
author = "@NiklasRosenstein"

[[entries]]
id = "0d3dacf6-741b-489f-ba9b-7456bd462f2f"
type = "improvement"
description = "`cargo clippy` actually builds your project, so we make it a subclass of `CargoBuildTask` and have it depend on the auth proxy and config sync"
author = "@NiklasRosenstein"

[[entries]]
id = "211c97c4-ed30-4b5c-908b-aa91bab3be2b"
type = "feature"
description = "add option to disable verify for build task"
author = "@NiklasRosenstein"

[[entries]]
id = "6d3153a7-7ce5-4038-8702-fa795143acb3"
type = "improvement"
description = "add `sccache(group)` parameter"
author = "@NiklasRosenstein"
