release-date = "2022-07-27"

[[entries]]
id = "68f545d1-d27c-4a69-880c-b10adb2bfb65"
type = "feature"
description = "add `CargoBumpVersionTask` and `cargo_publish(version)` argument"
author = "@NiklasRosenstein"
