release-date = "2022-07-21"

[[entries]]
id = "f8dc4c76-b79f-45c1-958e-bb2f819a2a41"
type = "feature"
description = "add `PythonSettings.always_use_managed_env` to ensure that Python tasks use the managed environment from the Python build system (instead of falling back to a currently active virtual environment)"
author = "@NiklasRosenstein"

[[entries]]
id = "b8065b60-4e51-43b8-8751-c690c92f42b7"
type = "fix"
description = "add `--non-interactive` to Twine upload"
author = "@NiklasRosenstein"

[[entries]]
id = "f9ae793e-ffc2-40aa-a7d4-12e2c2b772c1"
type = "feature"
description = "add `--log-cli-level` by default when running Pytest and take `PYTEST_FLAGS` into account"
author = "@NiklasRosenstein"

[[entries]]
id = "9182784b-8f03-43dd-bd6c-cd2fbab3cd66"
type = "tests"
description = "add integration tests for linting and publishing Poetry and Slap Python projects"
author = "@NiklasRosenstein"

[[entries]]
id = "5976bef8-278a-4d00-b27c-5d5a9937ba64"
type = "fix"
description = "update `PoetryPythonBuildSystem` to ignore the current virtual environment to ensure we get the path of the Poetry managed environment"
author = "@NiklasRosenstein"

[[entries]]
id = "e0108498-391f-4083-ad81-749691abc2f1"
type = "fix"
description = "`PoetryPythonBuildSystem` now injects package indexes and credentials into `pyproject.toml` and `poetry.toml` temporarily"
author = "@NiklasRosenstein"

[[entries]]
id = "5d4564de-dbce-4143-922d-a433c6940297"
type = "fix"
description = "Pass index URL and credentials to `slap install` command"
author = "@NiklasRosenstein"
