release-date = "2023-07-10"

[[entries]]
id = "3689a241-dd41-402b-a6ca-cddd3823d108"
type = "fix"
description = "mitmproxy: Stream HTTP body instead of buffering to completion"
author = "@wngr"
pr = "https://github.com/kraken-build/kraken-build/pull/71"
