release-date = "2022-09-13"

[[entries]]
id = "ea7f0cb8-182b-42a3-904c-685a96d04061"
type = "improvement"
description = "Use Kaniko 1.9.0 by default"
author = "@NiklasRosenstein"

[[entries]]
id = "8f59c5eb-e77a-45a8-9a1c-3e1d1ec646b2"
type = "feature"
description = "take `KRAKEN_CARGO_BUILD_FLAGS` into account"
author = "@NiklasRosenstein"
