release-date = "2022-09-14"

[[entries]]
id = "a543c7df-e894-45a6-a325-a732971a0ba0"
type = "improvement"
description = "The Python install task no longer needs to temporarily create a `poetry.toml` file because we now have the login task that should run before it."
author = "@NiklasRosenstein"
