release-date = "2023-10-10"

[[entries]]
id = "aa631280-287e-4773-9118-89619e9bd5e7"
type = "feature"
description = "Added buffrs login/install/generate to kraken.std. Allow cargo_build to depend on task(s), i.e. buffrs install"
author = "alex.spencer@helsing.ai"
pr = "https://github.com/kraken-build/kraken-build/pull/120"

[[entries]]
id = "8011b761-4b58-4c3a-ba34-8099e9a24b88"
type = "fix"
description = "Confine buf command to current working directory of project"
author = "alex.spencer@helsing.ai"
pr = "https://github.com/kraken-build/kraken-build/pull/122"
