release-date = "2022-12-12"

[[entries]]
id = "d3def3bf-1e0b-45d4-999e-cb02fdf0b6d6"
type = "feature"
description = "Add `cargo_build(workspace)` parameter"
author = "unknown"

[[entries]]
id = "74349729-bbf6-43b4-bc55-26aea7ba79bc"
type = "fix"
description = "Fix preserve workspace_memebers in cargo manifest"
author = "callumPearce"

[[entries]]
id = "91196d66-d55b-4e2c-85bb-fd16bfb236fc"
type = "fix"
description = "Have `PythonSettings.get_tests_directory()` return it only if it exists"
author = "@NiklasRosenstein"

[[entries]]
id = "27572d9b-2a0f-413c-9d58-2cf8ab5cfb72"
type = "fix"
description = "pass the path to the Black config file as an absolute path, this fixes an issue with running Black in a subproject where the CWD is different than when the build script is executed"
author = "@NiklasRosenstein"

[[entries]]
id = "4bb0d5bc-4675-41cd-8196-add8ac923664"
type = "fix"
description = "fix specifying the path to `pyproject.toml` in the `UpdatePyprojectTask` to be a path relative to the project directory"
author = "@NiklasRosenstein"
