release-date = "2022-10-05"

[[entries]]
id = "4f5d1bea-a579-4a0e-aab5-ff59b74b2b91"
type = "feature"
description = "Add `PythonIndex.publish` setting. Nothing in kraken-std currently consumes this setting."
author = "@NiklasRosenstein"

[[entries]]
id = "02f45570-4ace-4704-9076-596dfad51a37"
type = "feature"
description = "Add `kraken.std.python.pylint()`"
author = "Christopher-Steel<christopher.g.steel@gmail.com>"
