release-date = "2023-02-03"

[[entries]]
id = "ca9f489f-2375-4d55-aef2-b101e399b1b5"
type = "feature"
description = "Adds pycln task"
author = "@Tpt"

[[entries]]
id = "ed9e7987-5a84-492b-adb9-0f4314d69db4"
type = "feature"
description = "add `kraken.std.python.update_lockfile_task()`"
author = "@rbyshko"
