release-date = "2024-01-12"

[[entries]]
id = "2f2d584f-2a2a-49cc-b265-56e7b1ed3ce9"
type = "feature"
description = "Add `GetItemSupplier` and `Supplier.__getitem__()`"
author = "niklas.rosenstein@helsing.ai"

[[entries]]
id = "ee333218-60d5-438d-bcec-bee90bf3c2d2"
type = "improvement"
description = "Add `PexBuildTask.output_scripts_dir` and `.output_scripts` properties"
author = "niklas.rosenstein@helsing.ai"

[[entries]]
id = "c47a5861-45f1-4d42-b28a-ef725bf363f6"
type = "feature"
description = "add `NovellaTask()` and `novella()` factory function to build documentation with [Novella](https://github.com/NiklasRosenstein/novella/)"
author = "niklas.rosenstein@helsing.ai"
