release-date = "2022-12-19"

[[entries]]
id = "d174c5d0-5058-4864-a648-aa9239587b1b"
type = "fix"
description = "fix `deprecated_get_requirement_spec_from_file_header()` to avoid the default python path to be spread out as individual items in the `RequirementSpec.pythonpath`"
author = "@NiklasRosenstein"

[[entries]]
id = "c93b301d-6eec-47a3-bbd0-0ca6988396b9"
type = "fix"
description = "fix `deprecated_get_requirement_spec_from_file_header()` to avoid the default python path to be spread out as individual items in the `RequirementSpec.pythonpath`"
author = "@NiklasRosenstein"
