[[entries]]
id = "4c5a9a3a-7981-4a61-a3a9-a68661178ef0"
type = "feature"
description = "add `kraken.common.findpython` module which will be used by kraken-wrapper to find an applicable Python version per the interpreter constraint in the buildscript requirements."
author = "@NiklasRosenstein"
pr = "https://github.com/kraken-build/kraken-build/pull/42"

[[entries]]
id = "e368a217-723a-4936-9586-bf3cadfdfcd2"
type = "improvement"
description = "Set `DEFAULT_INTERPRETER_CONSTRAINT` to` >=3.10,<3.11`"
author = "@NiklasRosenstein"
pr = "https://github.com/kraken-build/kraken-build/pull/42"
