# This workflow is used to validate if the current version of kraken-core and kraken-std work without
# errors to build the kraken-std project. When some larger changes are being made to these two components,
# such as one that causes a breaking API change for the kraken-std build script, this workflow may need
# to be temporarily disabled.

name: "Selftest"

on:
  push: { branches: [ "develop" ], tags: [ "*" ] }
  pull_request: { branches: [ "*" ] }

env:
  COLUMNS: 200

jobs:
  selftest:
    runs-on: [ self-hosted ]
    steps:
    - uses: actions/checkout@v3
    - uses: NiklasRosenstein/slap@gha/install/v1
    - uses: actions/setup-python@v4
      with: { python-version: "3.10" }
    - run: pip install pipx && pipx install poetry && pipx install pdm
    - run: rustup update
    - run: slap install --link --no-venv-check ${{ matrix.only }}
    - run: cd kraken-build && kraken run fmt lint test -vv
    - run: cd kraken-build && kraken q ls
    - run: cd kraken-build && kraken q tree
    - run: cd kraken-build && kraken q viz
    - run: cd kraken-build && kraken q d python.mypy

  examples-docker-manual:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: NiklasRosenstein/slap@gha/install/v1
    - uses: actions/setup-python@v4
      with: { python-version: "3.10" }
    - run: slap install --link --no-venv-check ${{ matrix.only }}
    - run: cd examples/docker-manual && kraken run :dockerBuild :sub:helloWorld
